export const productMap = [{
    traditional: '美元/港币',
    code: '',
    simplified: '美元/港币',
    zone: 3,
    start: 0,
    end: 0,
    short_name: 'USDHKD',
    source: 'USDHKD.ref',
    code_id: 121001,
    digit: 5,
    groupSymbol: {},
    class: '',
},
{
    traditional: '美元加元',
    code: '',
    simplified: '美元加元',
    zone: 2,
    start: 0,
    end: 0,
    short_name: 'USD/CAD',
    source: 'USDCAD_Group',
    code_id: 4004,
    digit: 5,
    groupSymbol: {},
    class: '',
},
{
    traditional: '欧元美元',
    code: '',
    simplified: '欧元美元',
    zone: 2,
    start: 0,
    end: 0,
    short_name: 'EUR/USD',
    source: 'EURUSD_Group',
    code_id: 4011,
    digit: 5,
    groupSymbol: {},
    class: '',
},
{
    traditional: '美元/人民币',
    simplified: '美元/人民币',
    zone: 2,
    start: 0,
    end: 0,
    short_name: 'USD/CNY',
    source: 'USDCNY_Group',
    code_id: 132003,
    digit: 4,
    groupSymbol: {},
    class: '',
},
{
    traditional: '美元/港币',
    code: '',
    simplified: '美元/港币',
    zone: 3,
    start: 0,
    end: 0,
    short_name: 'USDHKD',
    source: 'USDHKD.ref',
    code_id: 121001,
    digit: 5,
    groupSymbol: {},
    class: '',
},
{
    traditional: '美元日元',
    simplified: '美元日元',
    zone: 2,
    start: 0,
    end: 0,
    short_name: 'USDJPY_Mini',
    source: 'USDJPY_Group',
    code_id: 193025,
    digit: 2,
    groupSymbol: {},
    class: '',
},
{
    traditional: '美元日元',
    simplified: '美元日元',
    zone: 2,
    start: 0,
    end: 0,
    short_name: 'USDJPY_Mini_2',
    source: 'USDJPY_Group',
    code_id: 313001,
    digit: 2,
    groupSymbol: {},
    class: '',
},
{
    traditional: '美元日元',
    simplified: '美元日元',
    zone: 2,
    start: 0,
    end: 0,
    short_name: 'USDJPY_Mini_3',
    source: 'USDJPY_Group',
    code_id: 313002,
    digit: 2,
    groupSymbol: {},
    class: '',
},
{
    traditional: '澳元日元',
    code: '',
    simplified: '澳元日元',
    zone: 2,
    start: 0,
    end: 0,
    short_name: 'AUD/JPY',
    source: 'AUDJPY_Group',
    code_id: 533002,
    digit: 3,
    groupSymbol: {},
    class: '',
},
{
    traditional: '澳元美元',
    simplified: '澳元美元',
    zone: 2,
    start: 0,
    end: 0,
    short_name: 'AUD/USD',
    source: 'AUDUSD_Group',
    code_id: 533003,
    digit: 5,
    groupSymbol: {},
    class: '',
},
{
    traditional: '美元日元',
    simplified: '美元日元',
    zone: 2,
    start: 0,
    end: 0,
    short_name: 'USD/JPY',
    source: 'USDJPY_Group',
    code_id: 533004,
    digit: 3,
    groupSymbol: {},
    class: '',
},
{
    traditional: '英镑澳元',
    simplified: '英镑澳元',
    zone: 2,
    start: 0,
    end: 0,
    short_name: 'GBP/AUD',
    source: 'GBPAUD_Group',
    code_id: 533007,
    digit: 5,
    groupSymbol: {},
    class: '',
},
{
    traditional: '英镑美元',
    simplified: '英镑美元',
    zone: 2,
    start: 0,
    end: 0,
    short_name: 'GBP/USD',
    source: 'GBPUSD_Group',
    code_id: 533010,
    digit: 5,
    groupSymbol: {},
    class: '',
},
{
    traditional: '道琼斯工业平均指数 30',
    simplified: '道琼斯工业平均指数 30',
    zone: 5,
    symbolIcon: '{"1":{"linkUrl":"","title":"","desc":""},"2":{"linkUrl":"","title":"","desc":""}}',
    start: 0,
    end: 0,
    short_name: 'DJ30ENG',
    source: 'IX_DJ30_202003',
    code_id: 533008,
    digit: 2,
    groupSymbol: {},
    class: 'ellipsis',
},
{
    traditional: '标普500',
    code: '',
    simplified: '标普500',
    zone: 5,
    symbolIcon: '{"1":{"linkUrl":"","title":"","desc":""},"2":{"linkUrl":"","title":"","desc":""}}',
    start: 0,
    end: 0,
    short_name: 'SP500',
    source: 'IX_SP500_202003',
    code_id: 533011,
    digit: 3,
    groupSymbol: {},
    class: '',
},
{
    traditional: '印度50',
    simplified: '印度50',
    zone: 5,
    symbolIcon: '{"1":{"linkUrl":"","title":"","desc":""},"2":{"linkUrl":"","title":"","desc":""}}',
    start: 0,
    end: 0,
    short_name: 'Nifty50',
    source: 'IH_Group',
    code_id: 553002,
    digit: 3,
    groupSymbol: {},
    class: '',
},
{
    traditional: '腾讯控股',
    code: '',
    simplified: '腾讯控股',
    zone: 7,
    start: 0,
    end: 0,
    short_name: '',
    source: '700_HK_IX',
    code_id: 553003,
    digit: 3,
    groupSymbol: {},
    class: '',
},
{
    traditional: '阿里巴巴-SW',
    code: '09988',
    simplified: '阿里巴巴-SW',
    zone: 7,
    start: 0,
    end: 0,
    short_name: '09988',
    source: '9988_HK_IX',
    code_id: 553004,
    digit: 3,
    groupSymbol: {},
    class: '',
},
{
    traditional: '银河娱乐',
    code: '00027',
    simplified: '银河娱乐',
    zone: 7,
    start: 0,
    end: 0,
    short_name: '00027',
    source: '27_HK_IX',
    code_id: 553005,
    digit: 3,
    groupSymbol: {},
    class: '',
},
{
    traditional: '百度',
    code: 'BIDU',
    simplified: '百度',
    zone: 9,
    start: 0,
    end: 0,
    short_name: 'BIDU',
    source: 'BIDU_US_IX',
    code_id: 553006,
    digit: 3,
    groupSymbol: {},
    class: '',
},
{
    traditional: '苹果公司',
    code: 'AAPL',
    simplified: '苹果公司',
    zone: 9,
    start: 0,
    end: 0,
    short_name: 'AAPL',
    source: 'AAPL_US_IX',
    code_id: 553007,
    digit: 3,
    groupSymbol: {},
    class: '',
},
{
    traditional: '现货黄金',
    simplified: '现货黄金',
    zone: 4,
    symbolIcon: '{"1":{"linkUrl":"","title":"","desc":""},"2":{"linkUrl":"","title":"","desc":""}}',
    start: 0,
    end: 0,
    short_name: 'XAUUSD',
    source: 'XAUUSD_Group.flo',
    code_id: 533005,
    digit: 2,
    groupSymbol: {},
    class: '',
},
{
    traditional: '现货白银',
    simplified: '现货白银',
    zone: 4,
    symbolIcon: '{"1":{"linkUrl":"","title":"","desc":""},"2":{"linkUrl":"","title":"","desc":""}}',
    start: 0,
    end: 0,
    short_name: 'XAGUSD',
    source: 'XAGUSD_Group.flo',
    code_id: 533006,
    digit: 3,
    groupSymbol: {},
    class: '',
},
{
    traditional: '美国原油',
    code: '',
    simplified: '美国原油',
    zone: 15,
    symbolIcon: '1',
    start: 0,
    end: 0,
    short_name: 'USOil',
    source: 'CL_Group',
    code_id: 553012,
    digit: 5,
    groupSymbol: {},
    class: '',
},
{
    traditional: '加元日元',
    simplified: '加元日元',
    zone: 2,
    start: 0,
    end: 0,
    short_name: 'CAD/JPY',
    source: 'CADJPY_Group',
    code_id: 533012,
    digit: 3,
    groupSymbol: {},
    class: '',
},
{
    traditional: '现货黄金',
    simplified: '现货黄金',
    zone: 4,
    start: 0,
    end: 0,
    short_name: 'XAUUSD_mini',
    source: 'XAUUSD_Group.flo',
    code_id: 293001,
    digit: 2,
    groupSymbol: {},
    class: '',
},
{
    traditional: '现货黄金',
    simplified: '现货黄金',
    zone: 4,
    start: 0,
    end: 0,
    short_name: 'XAUUSD_mini_2',
    source: 'XAUUSD_Group.flo',
    code_id: 313401,
    digit: 2,
    groupSymbol: {},
    class: '',
},
{
    traditional: '现货黄金',
    simplified: '现货黄金',
    zone: 4,
    start: 0,
    end: 0,
    short_name: 'XAUUSD_mini_3',
    source: 'XAUUSD_Group.flo',
    code_id: 313402,
    digit: 2,
    groupSymbol: {},
    class: '',
},
{
    traditional: '美国原油',
    simplified: '美国原油',
    zone: 5,
    start: 0,
    end: 0,
    short_name: 'USOil_Mini_3',
    source: 'CL_Group',
    code_id: 333001,
    digit: 2,
    groupSymbol: {},
    class: '',
},
{
    traditional: '美国原油',
    code: '',
    simplified: '美国原油',
    zone: 5,
    start: 0,
    end: 0,
    short_name: 'USOil',
    source: 'CL_Group',
    code_id: 163009,
    digit: 2,
    groupSymbol: {},
    class: '',
},
{
    traditional: '美国原油',
    simplified: '美国原油',
    zone: 5,
    start: 0,
    end: 0,
    short_name: 'USOil_Mini_2',
    source: 'CL_Group',
    code_id: 333002,
    digit: 2,
    groupSymbol: {},
    class: '',
},
{
    traditional: '京东',
    code: 'JD',
    simplified: '京东',
    zone: 9,
    start: 0,
    end: 0,
    short_name: '京东',
    source: 'JD_US_IX',
    code_id: 553008,
    digit: 3,
    groupSymbol: {},
    class: '',
},
{
    traditional: 'CORN',
    code: '',
    simplified: 'CORN',
    zone: 14,
    start: 0,
    end: 0,
    short_name: 'CORN',
    source: 'C_Group',
    code_id: 553011,
    digit: 5,
    groupSymbol: {},
    class: '',
},
]
